// study/my-sass-project/apps/react-app/src/features/asset/components/AssetChart.tsx
import { useEffect, useRef } from "react";
import * as echarts from "echarts/core";
import { BarChart } from "echarts/charts";
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
  DatasetComponent,
  TransformComponent,
} from "echarts/components";
import { LabelLayout, UniversalTransition } from "echarts/features";
import { CanvasRenderer } from "echarts/renderers";

echarts.use([
  TitleComponent,
  TooltipComponent,
  GridComponent,
  DatasetComponent,
  TransformComponent,
  BarChart,
  LabelLayout,
  UniversalTransition,
  CanvasRenderer,
]);

export interface ChartItem {
  name: string;
  value: number;
}

interface Props {
  title: string;
  data: ChartItem[];
  onBarClick?: (name: string) => void;
}

export default function AssetChart({ title, data, onBarClick }: Props) {
  const chartRef = useRef<HTMLDivElement | null>(null);
  const chartInstanceRef = useRef<echarts.ECharts | null>(null);

  // 初始化
  useEffect(() => {
    if (!chartRef.current) return;

    const chart = echarts.init(chartRef.current);
    chartInstanceRef.current = chart;

    const handleClick = (params: any) => {
      onBarClick?.(params?.name);
    };
    chart.on("click", handleClick);

    const handleResize = () => chart.resize();
    window.addEventListener("resize", handleResize);

    // 首次渲染
    chart.setOption({
      title: { 
        text: title, 
        left: "center", 
        top: 10,
        textStyle: { fontSize: 18, color: "#333", fontWeight: 'normal' } 
      },
      tooltip: { 
        trigger: "axis",
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderWidth: 0,
        boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
        textStyle: { color: "#333" }
      },
      grid: { 
        top: 70, 
        left: 20, 
        right: 20, 
        bottom: 20, 
        containLabel: true 
      },
      xAxis: { 
        type: "category", 
        data: data.map((i) => i.name),
        axisLabel: { color: "#666", fontSize: 12 },
        axisLine: { lineStyle: { color: "#eee" } }
      },
      yAxis: { 
        type: "value",
        splitLine: { lineStyle: { type: "dashed", color: "#f0f0f0" } },
        axisLabel: { color: "#999" }
      },
      series: [
        {
          type: "bar",
          data: data.map((i) => i.value),
          barWidth: "40%",
          showBackground: true,
          backgroundStyle: { color: "rgba(0,0,0,0.02)" },
          itemStyle: { 
            borderRadius: [6, 6, 0, 0],
            color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
              { offset: 0, color: "#4facfe" },
              { offset: 1, color: "#00f2fe" }
            ])
          },
          emphasis: {
            itemStyle: {
              color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                { offset: 0, color: "#2af598" },
                { offset: 1, color: "#009efd" }
              ])
            }
          }
        },
      ],
      animationDuration: 1500,
      animationEasing: "cubicOut"
    });

    return () => {
      window.removeEventListener("resize", handleResize);
      chart.off("click", handleClick);
      chart.dispose();
      chartInstanceRef.current = null;
    };
  }, []);

  // 数据变化更新
  useEffect(() => {
    const chart = chartInstanceRef.current;
    if (!chart) return;

    chart.setOption({
      title: { text: title },
      xAxis: { data: data.map((i) => i.name) },
      series: [{ data: data.map((i) => i.value) }],
    });
  }, [data, title]);

  return (
    <div
      ref={chartRef}
      style={{
        width: "100%",
        height: 320,
        borderRadius: 16,
        background: "rgba(255, 255, 255, 0.8)",
        backdropFilter: "blur(10px)",
        boxShadow: "0 8px 32px 0 rgba(31, 38, 135, 0.07)",
        border: "1px solid rgba(255, 255, 255, 0.18)",
        padding: "10px"
      }}
    />
  );
}

// study/my-sass-project/src/components/AssetChart.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";
// 1. 引入 echarts 核心模块，核心模块提供了 echarts 使用必须要的接口。
import * as echarts from 'echarts/core';
// 2. 引入柱状图图表，后缀名为 Chart
import { BarChart } from 'echarts/charts';
// 3. 引入提示框，标题，直角坐标系，数据集，内置数据转换器组件，后缀名为 Component
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
  DatasetComponent,
  TransformComponent
} from 'echarts/components';
// 4. 标签自动布局、全局过渡动画等特性
import { LabelLayout, UniversalTransition } from 'echarts/features';
// 5. 引入 Canvas 渲染器，注意引入 CanvasRenderer 或者 SVGRenderer 是必须的一步
import { CanvasRenderer } from 'echarts/renderers';
// 6. 注册必须的组件
echarts.use([
  TitleComponent,
  TooltipComponent,
  GridComponent,
  DatasetComponent,
  TransformComponent,
  BarChart, // 我们只用柱状图
  LabelLayout,
  UniversalTransition,
  CanvasRenderer
]);
const props = defineProps<{
    title: string;
    data: { name: string; value: number; }[];
}>();

const chartRef = ref<HTMLElement | null>(null);
let myChart: echarts.ECharts | null = null;

const emit = defineEmits(['bar-click']);
const initChart = () => {
    if (!chartRef.value) return;
    myChart = echarts.init(chartRef.value);

    myChart.on('click',(params) =>{
        emit('bar-click',params.name);
    })
    //封装图标组件时，父子组件的数据结构不一样时
    /*
    /组件纯洁性:
    1.屏蔽业务细节：AssetChart是通用的ui组件，不知道业务层详细数据，
    所以i.budget不能出现，
    2.数据转换层：父组件使用computed作为转换器，将特定业务对象数组映射标准化
    {name：value}格式
    3.双向契约：父组件父子归一化，子组件通过TS泛型严格约束输入契约
    */
    const option = {
        title: { text: props.title, left: 'center', textStyle: { fontSize: 16 } },
        tooltip: { trigger: 'axis' },
        grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
        xAxis: { type: 'category', data: props.data.map(i => i.name) },
        yAxis: { type: 'value' },
        series: [{
            //组件纯洁性
            data: props.data.map(i => i.value),
            type: 'bar',
            showBackground: true,
            backgroundStyle: { color: 'rgba(180, 180, 180, 0.2)' },
            itemStyle: { color: '#1890ff', borderRadius: [4, 4, 0, 0] }
        }]
    };
    myChart.setOption(option);
};

//处理窗口缩放
const handleResize = () => {
    myChart?.resize();
}
//监听数据变化刷新图表
watch(() => props.data, (newData) => {
    if (newData.length > 100) {
        console.warn('数据量过大，图标进入限流模式');
    }
    myChart?.setOption({
        xAxis: { data: props.data.map(i => i.name) },
        //数据归一化：父组件负责将业务数据（budget）“翻译”成子组件认识的标准数据value
        series: [{ data: props.data.map(i => i.value) }]
    });
}, { deep: false });
onMounted(() => {
    initChart();
    window.addEventListener('resize', handleResize);
});


//防止内存泄露
onUnmounted(() => {
    window.removeEventListener('resize', handleResize);
    myChart?.dispose();
});
</script>
<template>
    <div ref="chartRef" class="chart-container"></div>
</template>
<style scoped>
.chart-container {
    width: 100%;
    height: 300px;
    padding: 15px;
    border-radius: 8px;
    background: #fff;

}
</style>
