// study/my-sass-project/apps/react-app/src/features/asset/components/VirtualTable.tsx
import React, { useMemo, useState, useRef, useEffect, useCallback } from "react";

interface VirtualTableProps<T extends { id: number | string }> {
    data: T[];
    itemHeight?: number;
    viewHeight: number;
    onRowClick?: (row: T) => void;
    renderRow: (row: T) => React.ReactNode;
}

const TableRow = React.memo(({ children, height, onClick }: { children: React.ReactNode, height: number, onClick: () => void }) => (
    <div
        style={{ width: "100%", boxSizing: "border-box", height }}
        onClick={onClick}
    >
        {children}
    </div>
));

export default function VirtualTable<T extends { id: number | string }>(props: VirtualTableProps<T>) {
    const { data, itemHeight = 50, viewHeight, onRowClick, renderRow } = props;
    const [scrollTop, setScrollTop] = useState(0);
    const scrollContainerRef = useRef<HTMLDivElement>(null);
    const requestRef = useRef<number>(0);

    const onScroll = useCallback(() => {
        if (scrollContainerRef.current) {
            const currentScrollTop = scrollContainerRef.current.scrollTop;
            if (requestRef.current) cancelAnimationFrame(requestRef.current);
            requestRef.current = requestAnimationFrame(() => {
                setScrollTop(currentScrollTop);
            });
        }
    }, []);

    useEffect(() => {
        return () => {
            if (requestRef.current) cancelAnimationFrame(requestRef.current);
        };
    }, []);

    const phantomHeight = data.length * itemHeight;
    const visibleCount = Math.ceil(viewHeight / itemHeight) + 3; // 稍微多预留一点缓冲区

    const startIndex = Math.floor(scrollTop / itemHeight);
    const endIndex = Math.min(startIndex + visibleCount, data.length);
    
    const visibleData = useMemo(() => {
        return data.slice(startIndex, endIndex);
    }, [data, startIndex, endIndex]);

    const offsetY = startIndex * itemHeight;

    return (
        <div
            ref={scrollContainerRef}
            style={{
                overflowY: "auto",
                position: "relative",
                background: "transparent",
                height: viewHeight,
                willChange: "transform",
                contain: "strict"
            }}
            onScroll={onScroll}
        >
            <div style={{ height: phantomHeight, pointerEvents: 'none' }} />
            <div
                style={{
                    position: "absolute",
                    left: 0,
                    right: 0,
                    top: 0,
                    transform: `translate3d(0, ${offsetY}px, 0)`,
                }}
            >
                {visibleData.map((item) => (
                    <TableRow 
                        key={item.id} 
                        height={itemHeight} 
                        onClick={() => onRowClick?.(item)}
                    >
                        {renderRow(item)}
                    </TableRow>
                ))}
                {data.length === 0 && (
                    <div style={{ textAlign: "center", color: "#909399", padding: 40 }}>暂无匹配数据</div>
                )}
            </div>
        </div>
    );
}

// study/my-sass-project/apps/vue-app/src/components/VirtualTable.vue
<script setup lang="ts" generic="T extends { id: number | string }">
import { ref, computed } from 'vue';

const props = withDefaults(defineProps<{
  data: T[];
  itemHeight: number;
  viewHeight: number;
}>(), {
  data: () => [],
  itemHeight: 50
})

const emit = defineEmits(['row-click']);
const scrollTop = ref(0);

const phantomHeight = computed(() => props.data.length * props.itemHeight);
const visibleCount = computed(() => Math.ceil(props.viewHeight / props.itemHeight) + 2);
const startIndex = computed(() => Math.floor(scrollTop.value / props.itemHeight));
const endIndex = computed(() => startIndex.value + visibleCount.value);
const visibleData = computed(() => props.data.slice(startIndex.value, endIndex.value));
const offsetY = computed(() => startIndex.value * props.itemHeight);

const handleScroll = (e: Event) => {
  scrollTop.value = (e.target as HTMLElement).scrollTop;
};
</script>

<template>
  <div class="v-table-container" :style="{ height: viewHeight + 'px' }" @scroll="handleScroll">
    <div class="v-table-phantom" :style="{ height: phantomHeight + 'px' }"></div>
    <div class="v-table-content" :style="{ transform: `translateY(${offsetY}px)` }">
      <div v-for="item in visibleData" :key="item.id" class="v-row-box" :style="{ height: itemHeight + 'px' }"
        @click="emit('row-click', item)">
        <slot :row="item"></slot>
      </div>
      <div v-if="data.length === 0" class="no-data">暂无匹配数据</div>
    </div>
  </div>
</template>

<style scoped>
.v-table-container {
  overflow-y: auto;
  position: relative;
  background: #fff;
}

.v-table-phantom {
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  z-index: -1;
}

.v-table-content {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
}

.v-row-box {
  width: 100%;
  box-sizing: border-box;
}

/* 🚀 纯净容器 */
.no-data {
  text-align: center;
  color: #909399;
  padding: 40px;
}
</style>
